### ISSUE TITLE
does not work alongside Fabric, using cocoapods

### ISSUE THREAD

**Issue by ir-fuel** [TechSmith/CrashlyticsLumberjack#11]
podfile:

pod 'CocoaLumberjack', '~> 2.0'
pod 'CrashlyticsLumberjack', '2.0.1-beta'
pod 'Fabric/Core', '~> 1.3'
pod 'Fabric/Crashlytics', '~> 1.3'

when running `pod install` I get:

[!] The 'Pods' target has frameworks with conflicting names: Crashlytics.

**Comment by warpling** [comment]
Bump!

**Comment by waltflanagan** [comment]
I need more info about what is going wrong.  The mentioned pods are no longer supported.

**Comment by warpling** [comment]
I'm embarrassed to say I can't remember how I finally fixed this. It might have simply been from updating CocoaLumberjack. Anyway, all good now using `CocoaLumberjack (2.0.1)` and Fabric installed via their dashboard app.
