### ISSUE TITLE
Podspec still says 2.0.1-beta instead of 2.0.2

### ISSUE THREAD

**Issue by williamsjj** [TechSmith/CrashlyticsLumberjack#15]
CocoaPods still installs 2.0.1-beta with the broken CrashlyticsFramework reference instead of 2.0.2 that relies on the Fabric Crashlytics pod.

**Comment by waltflanagan** [comment]
I just pushed the updated version to cocoapods.  Should be processed and published in a bit.

**Comment by williamsjj** [comment]
Thanks @waltflanagan
