### ISSUE TITLE
CocoaLumberjack 2.2.0+ support?

### ISSUE THREAD

**Issue by donholly** [TechSmith/CrashlyticsLumberjack#17]
Are there plans to support the latest version of CocoaLumberjack?

**Comment by waltflanagan** [comment]
now that I know that there is a latest version, yea.  I'll try to do this today or friday.

**Comment by waltflanagan** [comment]
If you have time tho, feel free to fork and PR the update.  there likely wont be any conflict and it's just a matter of needed to rev the dependency in the podspec.

**Comment by donholly** [comment]
Coming up in a moment!

**Comment by donholly** [comment]
https://github.com/TechSmith/CrashlyticsLumberjack/pull/18

**Comment by waltflanagan** [comment]
Thanks, will get it merged and push to cocoapods soon
