### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by DMAPro** [TechSmith/CrashlyticsLumberjack#19]
Hallo!
I was wondering, why was the required iOS version changed to 8.0 in [this commit](https://github.com/TechSmith/CrashlyticsLumberjack/commit/5a87f602b5b594351862bfbfcdc412ac4d5e8973)? CocoaLumberjack supports iOS 5.0+, and Crashlytics supports iOS 6.0+. So, why 8.0?
5.x or 6.x support might be a bit extreme now, but there are [about 10%](https://david-smith.org/iosversionstats/) of users with iOS 7 left. That's a lot.
Is it possible to change the required iOS version to 7.0?
I would like to use the latest CocoaLumberjack along with the latest CrashlyticsLumberjack. But since the deployment target of my project is set to 7.0, CrashlyticsLumberjack 1.0.1 is downloaded.

P.S. Thank you for your the the great tool you've made!

**Comment by DMAPro** [comment]
P.P.S. All the above is about installing via CocoaPods.

**Comment by waltflanagan** [comment]
IIRC the Crashlytics framework was 8.0+ at the time.  Looking now that seems to have changed.

**Comment by waltflanagan** [comment]
I pushed a new version (2.0.5) that should fix this

**Comment by DMAPro** [comment]
@waltflanagan, yes, it works, thank you very much! :)
