### ISSUE TITLE
Please add support for CocoaLumberjack 3.0.0

### ISSUE THREAD

**Issue by k06a** [TechSmith/CrashlyticsLumberjack#20]
👍

**Comment by waltflanagan** [comment]
Are you just seeing an issue with the dependency on `~>2.2`?  I won't have time to play with this for a bit, so more info and PR's are welcome.

**Comment by k06a** [comment]
@waltflanagan I think it is ready for the merge :)
https://github.com/TechSmith/CrashlyticsLumberjack/pull/21

**Comment by k06a** [comment]
Any problems with PR?

**Comment by waltflanagan** [comment]
The updated spec has been pushed to cocoapods trunk.
